config/routes.rb
NexinnovaNew::Application.routes.draw do
  devise_for :users

  resources :ads

  resources :articles do 
    resources :comments
  end

  resources :pages
  
  root :to => "pages#index"

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  attr_accessible :image, :link
   has_attached_file :image 
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :content, :author, :tag, :featured, :approved, :page_id, :image
   has_attached_file :image
   has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  belongs_to :article
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :title, :color, :description
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable, :rpx_connectable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation 
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  def index
    @ads = Ad.all
  end

  def show
    @ad = Ad.find(params[:id])
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new(params[:ad])
    if @ad.save
    redirect_to @ad, :notice => "Successfully created ad."
    else
    render :action => 'new'
    end
  end

  def edit
    @ad = Ad.find(params[:id])
  end

  def update
    @ad = Ad.find(params[:id])
    if @ad.update_attributes(params[:ad])
    redirect_to @ad, :notice  => "Successfully updated ad."
    else
    render :action => 'edit'
    end
  end

  def destroy
    @ad = Ad.find(params[:id])
    @ad.destroy
    redirect_to ads_url, :notice => "Successfully destroyed ad."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :pages, :ads, :display_articles ,:latest_articles, :all_sorted_articles, :articles
  def pages
    @pages ||= Page.all
  end

  def ads
    @ads ||= Ad.all
  end
  
   def articles
    @articles ||= Article.all

  end
  
  def display_articles
    @display_articles ||= Article.all # paginate(:page => params[:page], :per_page => 10).scoped.order("created_at DESC")

  end

  def latest_articles
    @latest_articles ||= Article.limit(3).scoped.order("created_at DESC")
  end

  def all_sorted_articles
    @all_sorted_articles ||= Article.scoped.order("created_at DESC")
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index

    @articles = Article.all
  end

  def show
    
    @article = Article.find(params[:id])
      @comments = @article.comments.paginate :page => params[:page], :per_page => 10, :order => 'created_at ASC'  
  end

  def new

    @article = Article.new
  end

  def create

    @article = Article.new(params[:article])
    if @article.save
    redirect_to @article, :notice => "Successfully created article."
    else
    render :action => 'new'
    end
  end

  def edit

    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
    redirect_to @article, :notice  => "Successfully updated article."
    else
    render :action => 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_url, :notice => "Successfully destroyed article."
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create  
    article = Article.find params[:article_id]  
    comment = article.comments.new params[:comment]  
    comment.save  
    flash[:notice] = 'Comment saved'  
    redirect_to article_path(article)  
  end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(params[:page])
    if @page.save
      redirect_to @page, :notice => "Successfully created page."
    else
      render :action => 'new'
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(params[:page])
      redirect_to @page, :notice  => "Successfully updated page."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    redirect_to pages_url, :notice => "Successfully destroyed page."
  end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ads/_form.html.erb
<%= form_for @ad , :html => { :enctype => "multipart/form-data" }  do |f| %>
<table>
	<tr>
		<td colspan="2"> <%= f.error_messages %> </td>
	</tr>
	<tr>
		<td><%= f.label :image , :style => "text-align: left"  %></td>
		<td> <%= f.file_field :image ,  :class => 'span6' %></td>
	</tr>
	<tr>
		<td> <%= f.label :link , :style => "text-align: left"  %></td>
		<td> <%= f.text_field :link ,  :class => 'span6'%></td>
	</tr>
	<tr>
		<td></td>
		<td> <%= f.submit :class => "btn primary large" %></td>
	</tr>
</table>
<% end %> 

app/views/ads/edit.html.erb
<% title "Edit Ad" %>
<div class="middle">
	<div class="container_24">
		<!-- featured list -->
		<div class="divider_thin"></div>
		<!--content -->
		<div class="grid_15 suffix_1 content">
			<ul class="breadcrumb">
				<li>
					<a href="#">Edit Advertisment
				</li>
			</ul>
			<%= render 'form' %>
			<p>
				<%= link_to "Show", @ad %> |
				<%= link_to "View All", ads_path %>
			</p>
		</div>
		<!--/content -->
		<!-- sidebar-->
		<%= render "shared/sidebar" %> <!--/ sidebar -->
		<div class="clear"></div>
	</div>
</div>
<!--/ middle -->
<!-- bottom content/widgets -->
<%= render "shared/bottomcontent" %> <!--/ bottom content/widgets -->
<%= render "shared/footer" %>
</body>
</html> 

app/views/ads/index.html.erb
<% title "Ads" %>
<div class="middle">
	<div class="container_24">
		<!-- featured list -->
		<div class="divider_thin"></div>
		<!--content -->
		<div class="grid_15 suffix_1 content">
			<table class="zebra-striped">
				<tr>
					<th>Image</th>
					<th>Link</th>
				</tr>
				<% for ad in @ads %>
				<tr>
					<td><%= ad.image %></td>
					<td><%= ad.link %></td>
					<td><%= link_to "Show", ad , :class => "btn info" %></td>
					<td><%= link_to "Edit", edit_ad_path(ad)  , :class => "btn success" %></td>
					<td> <%= link_to "Destroy", ad_path(ad, :destroy => true),:confirm =>"Are you sure?", :method => :delete  , :class => "btn danger" %></td>
				</tr>
				<% end %>
			</table>
			<p>
				<%= link_to "New Ad", new_ad_path %>
			</p>
		</div>
		<!--/content -->
		<!-- sidebar-->
	
		<div class="clear"></div>
	</div>
</div>

app/views/ads/new.html.erb
<% title "New Ad" %>
<div class="middle">
	<div class="container_24">
		<!-- featured list -->
	<div class="divider_thin"></div>
		<!--content -->
		<div class="grid_15 suffix_1 content">
			<ul class="breadcrumb">
				<li>
					<a href="#">Add a Advertisement
				</li>
			</ul>
			<%= render 'form' %>
			<p>
				<%= link_to "Back to List", ads_path %>
			</p>
		</div>
		<!--/content -->
		<!-- sidebar-->
		<%= render "shared/sidebar" %> <!--/ sidebar -->
		<div class="clear"></div>
	</div>
</div>

app/views/ads/show.html.erb
<% title "Ad" %>
<div class="middle">
	<div class="container_24">
		<!-- featured list -->
		<div class="divider_thin"></div>
		<!--content -->
		<div class="grid_15 suffix_1 content">
			<p>
				<strong>Image:</strong>
				<%= image_tag(@ad.image.url) %>
			</p>
			<p>
				<strong>Link:</strong>
				<%= @ad.link %>
			</p>
			<p>
				<%= button_to "Edit", edit_ad_path(@ad), :class => "btn primary" %> 
				<%= button_to "Destroy", @ad, :confirm => 'Are you sure?', :method => :delete, :class => "btn primary" %> 
				<%= button_to "View All", ads_path , :class => "btn primary" %>
			</p>
		</div>
		<!--/content -->
		<!-- sidebar-->
		<%= render "shared/sidebar" %> <!--/ sidebar -->
		<div class="clear"></div>
	</div>
</div>

app/views/articles/_form.html.erb
<%= form_for @article , :html => { :enctype => "multipart/form-data" }  do |f| %>
<table>
	<tr>
		<td colspan="2"> <%= f.error_messages %> </td>
	</tr>
	<tr>
		<td> <%= f.label :title , :style => "text-align: left" %></td>
		<td> <%= f.text_field :title, :class => 'span6' %></td>
	</tr>
	<tr>
		<td><%= f.label :content,  :style => "text-align: left"  %></td>
		<td> <%= f.text_area :content,  :class => 'span7' %></td>
	</tr>
	<tr>
		<td><%= f.label :author , :style => "text-align: left"  %></td>
		<td> <%= f.text_field :author, :class => 'span6' %></td>
	</tr>
	<tr>
		<td><%= f.label :tag , :style => "text-align: left" %> </td>
		<td> <%= f.text_field :tag, :class => 'span6' %></td>
	</tr>
	<tr>
		<td> <%= f.label :featured, :style => "text-align: left"  %> </td>
		<td> <%= f.check_box :featured %> </td>
	</tr>
	<tr>
		<td><%= f.label :approved , :style => "text-align: left"  %> </td>
		<td> <%= f.check_box :approved %></td>
	</tr>
	<tr>
		<td> <%= f.label :page_id , :style => "text-align: left" %> </td>
		<td> <%= f.text_field :page_id, :class => 'span6' %></td>
	</tr>
	<tr>
		<td> <%= f.label :image, "Image" , :style => "text-align: left"  %></td>
		<td><%= f.file_field :image, :class => 'span6' %></td>
	</tr>
	<tr>
		<td></td>
		<td> <%= f.submit :class => "btn primary large"  %></td>
	</tr>
	<% end %>
</table>

app/views/articles/edit.html.erb
<% title "Edit Article" %>
<div class="middle">
	<div class="container_24">
		<!-- featured list -->
		<div class="divider_thin"></div>
		<!--content -->
		<div class="grid_15 suffix_1 content">
			<p>
				<strong>Image:</strong>
				<%= @ad.image %>
			</p>
			<p>
				<strong>Link:</strong>
				<%= @ad.link %>
			</p>
			<p>
				<%= link_to "Edit", edit_ad_path(@ad) %> |
				<%= link_to "Destroy", @ad, :confirm => 'Are you sure?', :method => :delete %> |
				<%= link_to "View All", ads_path %>
			</p>
		</div>
		<!--/content -->
		<!-- sidebar-->
		<%= render "shared/sidebar" %> <!--/ sidebar -->
		<div class="clear"></div>
	</div>
</div>
<ul class="breadcrumb">
  <li><a href="#">Edit Article
  	</li>

</ul>
<%= render 'form' %>

<p>
  <%= link_to "Show", @article %> |
  <%= link_to "View All", articles_path %>
</p>

app/views/articles/index.html.erb
<% title "Articles" %>
<div class="middle">
	<div class="container_24">
		<!-- featured list -->
		<div class="divider_thin"></div>
		<!--content -->
		<div class="grid_15 suffix_1 content">
			<table class="zebra-striped">
				<tr>
					<th>Title</th>
					<th>Content</th>
					<th>Author</th>
					<th>Tag</th>
					<th>Featured</th>
					<th>Approved</th>
					<th>Page</th>
				</tr>
				<% for article in @articles %>
				<tr>
					<td><%= article.title %></td>
					<td><%= article.content %></td>
					<td><%= article.author %></td>
					<td><%= article.tag %></td>
					<td><%= article.featured %></td>
					<td><%= article.approved %></td>
					<td><%= article.page_id %></td>
					<td><%= button_to "Show", article , :class => "btn primary" %></td>
					<td><%= button_to "Edit", edit_article_path(article) , :class => "btn success" %></td>
					<td> <%= button_to "Destroy", article_path(article	, :destroy => true),:confirm =>"Are you sure?", :method => :delete , :class => "btn danger" %></td>
				</tr>
				<% end %>
			</table>
			<p>
				<%= link_to "New Article", new_article_path , :class => "btn primary large	" %>
			</p>
		</div>
		<!--/content -->
		<!-- sidebar-->
		<div class="clear"></div>
	</div>
</div>

app/views/articles/new.html.erb
<% title "New Article" %>
<div class="middle">
	<div class="container_24">
		<!-- featured list -->
		<div class="divider_thin"></div>
		<!--content -->
		<div class="grid_15 suffix_1 content">
			<ul class="breadcrumb">
				<li>
					<a href="#">Add an Article
				</li>
			</ul>
			<%= render 'form' %>
			<p>
				<%= link_to "Back to List", articles_path %>
			</p>
		</div>
		<!--/content -->
		<!-- sidebar-->
		<%= render "shared/sidebar" %> <!--/ sidebar -->
		<div class="clear"></div>
	</div>
</div>

app/views/articles/show.html.erb
<div class="middle">
	<div class="container_24">
		<!-- featured list -->
		<div class="divider_thin"></div>
		<!--content -->
		<div class="grid_15 suffix_1 content">
			<div class="cat_title back_post">
				<a href="blog.html" class="link-back">&lt; back to articles</a>
				<div class="social_buttons_top">
					<%= image_tag("temp/social_buttons.gif", :size => '217x20' )%>
				</div>
				<div class="clear"></div>
			</div>
			<!-- post details -->
			<div class="post-item post-detail">
				<h1><%= @article.title %></h1>
				<div class="post-meta">
					<span class="icon_cat icon_cat_blog"><a href="#">Blog</a></span>
					<em>by <span class="author"><%= @article.author %> </span> &nbsp;|&nbsp; on <%= @article.created_at.to_s(:long) %> &nbsp;|&nbsp; <a href="#" class="link-comments"><%= @article.comments.count %> comments</a></em>
				</div>
				<div class="entry">
					<p>
						<%= image_tag @article.image.url , :size => '590x206' %>
					</p>
					<%= @article.content %> <div class="clear"></div>
				</div>
			</div>
			<!--/ post details -->
			<!-- post comments -->
			<div class="comment-list" id="comments">
				<a href="#addcomments" class="link-addcomment">Add a comment</a>
				<% if @comments %> <h2>Comments (<%= @article.comments.count %>)</h2>
				<ol>
					<% for comment in @article.comments %>
					<li class="comment">
						<div class="comment-body">
							<div class="avatar">
								<%= image_tag("avatar_default.gif", :size => '40x40' )%>
							</div>
							<div class="comment-text">
								<div class="comment-author">
									<a href="#" class="link-author"><%= comment.author %></a> <%= comment.created_at.to_s(:long)%>
								</div>
								<div class="comment-entry">
									<%= comment.text %>
								</div>
							</div>
							<div class="clear"></div>
						</div>
					</li>
					<% end %>
					<%= will_paginate @comments %>
					<% end %>
				</ol>
			</div>
			<!--/ post comments -->
			<!-- add comment -->
			<div class="add-comment" id="addcomments">
				<h3>Add a comment</h3>
				<table>
					<%= form_for([@article, Comment.new]) do |form| %>
					<tr>
						<td>Your name (required)</td>
						<td> <%= form.text_field :author, :class => "inputtext input_middle required" %> </td>
					</tr>
					<tr>
						<td>Your message</td>
						<td> <%= form.text_area :text, :class => "span6", :rows => "5"  %></td>
					</tr>
					<tr>
						<td></td>
						<td><%= form.submit 'Add Your Voice', :class => 'btn primary' %></td>
					</tr>
					<% end %>
				</table>
			</div>
			<!--/add comment -->
		</div>
		<!--/content -->
		<!-- sidebar-->
		<%= render "shared/sidebar" %>
	
		<div class="clear"></div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<%= stylesheet_link_tag :all, :recursive => true %>
		<%= javascript_include_tag "js/jquery.min.js" %> 
		<%= javascript_include_tag "js/preloadCssImages.js" %> 
		<%= javascript_include_tag "js/jquery.tools.min.js" %> 
		<%= javascript_include_tag "js/genaral.js" %> 
		<%= javascript_include_tag "js/jquery.featureList-1.0.0.js" %>
		
		<script type="text/javascript">
			$(document).ready(function() {
				$.featureList($("#feature_tabs li"), $("#feature_output li"), {
					start_item : 0,
					transition_interval : 5000
				});
			});

		</script>
		<%= csrf_meta_tag %>
		<%= yield(:head) %> <!--[if IE 6]>
		<script type="text/javascript" src="js/jquery.reject.min.js"></script>
		<script type="text/javascript">
		$(document).ready(function() {
		$.reject({
		close: false,
		imagePath: 'images/'
		});
		});
		</script>
		<![endif]-->
	</head>
	<body>
		<%= render "shared/headbar" %> <!--/ head menu -->
		<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, :id => "flash_#{name}", :class => "alert-message info container_24", :style => "margin:auto"  %>
		<% end %>

		<%= render "shared/header" %> <!--/ header -->
		<!-- middle -->
		<%= yield %> <!--/ middle -->
		<!-- bottom content/widgets -->
		<%= render "shared/bottomcontent" %> <!--/ bottom content/widgets -->
		<%= render "shared/footer" %>
		<%= javascript_include_rpx(user_session_url) %>
	</body>
</html>
<!DOCTYPE html>
<html>
	<head>
		<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
		<%= stylesheet_link_tag :all %>
		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
		<%= yield(:head) %>
	</head>
	<body>
		<div id="container">
			<div id="user_nav">
				<% if user_signed_in? %>
				Signed in as <%= current_user.email %>. Not you?
				<%= link_to "Sign out", destroy_user_session_path %>
				<% else %>
				<%= link_to "Sign up", new_user_registration_path %> or
				<%= link_to "Sign in", new_user_session_path %> or
				<%= link_to_rpx "Sign in with Facebook or Twitter	", user_session_url %>
				<% end %>
			</div>
			<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, :id => "flash_#{name}" %>
			<% end %>
			<%= content_tag :h1, yield(:title) if show_title? %>
			<%= yield %>
		</div>
		<%= javascript_include_rpx(user_session_url) %>
	</body>
</html>

app/views/pages/_form.html.erb
<%= form_for @page do |f| %>
<table>
	<tr>
		<td colspan="2"><%= f.error_messages %></td>
	</tr>
	<tr>
		<td> <%= f.label :title , :style => "text-align: left" %> </td>
		<td><%= f.text_field :title ,  :class => 'span6'%></td>
	</tr>
	<tr>
		<td> <%= f.label :color , :style => "text-align: left"  %> </td>
		<td> <%= f.text_field :color ,  :class => 'span6'%></td>
	</tr>
	<tr>
		<td> <%= f.label :description  , :style => "text-align: left" %> </td>
		<td> <%= f.text_area :description ,  :class => 'span7'%></td>
	</tr>
	<tr>
		<td></td>
		<td><%= f.submit  :class => "btn primary large" %></td>
	</tr>
	
</table>	
	

<% end %> 

app/views/pages/edit.html.erb
<% title "Edit Page" %>
<div class="middle">
	<div class="container_24">
		<!-- featured list -->
		<div class="divider_thin"></div>
		<!--content -->
		<div class="grid_15 suffix_1 content">
			<ul class="breadcrumb">
				<li>
					<a href="#">Edit Page
				</li>
			</ul>
			<%= render 'form' %>
			<p>
				<%= link_to "Show", @page %> |
				<%= link_to "View All", pages_path %>
			</p>
		</div>
		<!--/content -->
		<!-- sidebar-->
		<%= render "shared/sidebar" %> <!--/ sidebar -->
		<div class="clear"></div>
	</div>
</div>

app/views/pages/index.html.erb
<% title "Nexinnova Home" %>
<div class="middle">
	<div class="container_24">
		<!-- featured list -->
		<%= render "shared/feature" %>
		<div class="divider_thin"></div>
		<!--content -->
		<div class="grid_15 suffix_1 content">
			<div class="cat_title">
				<h2>Latest Posts</h2>
				<!-- <div class="sort">
				<a href="#">Popular</a><a href="#" class="active">By Date</a>
				</div> -->
				<div class="clear"></div>
			</div>
			<% for article in @display_articles %>
			<div class="post-item">
				<h2><%= link_to article.title, article_path(article) %></a></h2>
				<div class="post-meta">
					<span class="icon_cat icon_cat_2"><a href="#"><%= article.tag %></a></span>
					<em>by <span class="author"><%= article.author %></span> &nbsp;|&nbsp; on <%= article.created_at.to_s(:long) %> &nbsp;|&nbsp; <a href="#" class="link-comments"> comments</a></em>
				</div>
				<div class="entry">
					<p>
						<%= image_tag article.image.url ,:size => '305x206', :class => 'alignleft' %>
					</p>
					<p style="text-align: justify">
						<%= truncate(article.content, :length => 400 , :ommision => "...") %>
					</p>
					<div class="clear"></div>
				</div>
				<%= link_to "read more", article, :class => "link-more" %>
			</div>
			<% end %>
		</div>
		<!--/content -->
		<!-- sidebar-->
		<%= render "shared/sidebar" %> <!--/ sidebar -->
		<div class="clear"></div>
	</div>
</div>

app/views/pages/new.html.erb
<% title "New Page" %>
<div class="middle">
	<div class="container_24">
		<!-- featured list -->
		<div class="divider_thin"></div>
		<!--content -->
		<div class="grid_15 suffix_1 content">
			<ul class="breadcrumb">
				<li>
					<a href="#">Add a Page
				</li>
			</ul>
			<%= render 'form' %>
			<p>
				<%= link_to "Back to List", pages_path %>
			</p>
		</div>
		<!--/content -->
		<!-- sidebar-->
		<%= render "shared/sidebar" %> <!--/ sidebar -->
		<div class="clear"></div>
	</div>
</div>

app/views/pages/show.html.erb
<% title "Page" %>
<div class="middle">
	<div class="container_24">
		<!-- featured list -->
		<div class="divider_thin"></div>
		<!--content -->
		<div class="grid_15 suffix_1 content">
			<div class="cat_title">
				<h2>Latest Posts</h2>
				<!-- <div class="sort">
				<a href="#">Popular</a><a href="#" class="active">By Date</a>
				</div> -->
				<div class="clear"></div>
			</div>
			<% for article in @display_articles %>
			<div class="post-item">
				<h2><%= link_to article.title, article_path(article) %></a></h2>
				<div class="post-meta">
					<span class="icon_cat icon_cat_2"><a href="#"><%= article.tag %></a></span>
					<em>by <span class="author"><%= article.author %></span> &nbsp;|&nbsp; on <%= article.created_at.to_s(:long) %> &nbsp;|&nbsp; <a href="#" class="link-comments"> comments</a></em>
				</div>
				<div class="entry">
					<p>
						<%= image_tag article.image.url ,:size => '305x206', :class => 'alignleft' %>
					</p>
					<p style="text-align: justify">
						<%= truncate(article.content, :length => 400 , :ommision => "...") %>
					</p>
					<div class="clear"></div>
				</div>
				<%= link_to "read more", article, :class => "link-more" %>
			</div>
			<% end %>
		</div>
		<!--/content -->
		<!-- sidebar-->
		<%= render "shared/sidebar" %> <!--/ sidebar -->
		<div class="clear"></div>
	</div>
</div>

app/views/shared/_bottomcontent.html.erb
<div class="bottom_content">
	<div class="container_24">
		<div class="inner">
			<div class="grid_6">
				<div class="widget">
					<ul class="menu_type_1">
						<% for page in @pages %>
						<li>
							<%= link_to page.title, page_path(page) %>
						</li>
						<% end %>
					</ul>
				</div>
			</div>
			<div class="grid_6">
				<div class="widget">
					<h3>NETWORK</h3>
					<ul class="menu_type_2">
						<li>
							<a href="#">All Sports Mag</a>
						</li>
						<li>
							<a href="#">Car Tuning Mag</a>
						</li>
						<li>
							<a href="#">For Her Magazine</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="grid_6">
				<div class="widget">
					<h3>BLOG</h3>
					<ul class="menu_type_2">
						<li>
							<a href="#">We've redesigned the blog...</a>
						</li>
						<li>
							<a href="#">Saving everything in your...</a>
						</li>
						<li>
							<a href="#">Make it right, now!</a>
						</li>
						<li>
							<a href="#">Asylum of fools discovered</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="grid_6">
				<div class="widget">
					<h3>MAGAZINE</h3>
					<ul class="menu_type_2">
						<li>
							<a href="#">Our authors</a>
						</li>
						<li>
							<a href="#">Monthly Archive</a>
						</li>
						<li>
							<a href="#">Advertise</a>
						</li>
						<li>
							<a href="#">Jobs &amp; Careers</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>